### ISSUE TITLE
The feet of the VRM model have some problems when doing some movements.

### ISSUE THREAD

**Issue by wangjiangs** [JLChnToZ/vrm-dance-viewer#1]
when i use a vmd animation file to any  vrm model, there is some thing wrong with foot as follow picture. 
I found that this problem is related to this code。a const value `IK_OFFSET_INIT`.

`
const IK_OFFSET_INIT = new Map<VMDBoneNames, IKOffsetInit>([

  [VMDBoneNames.Center, { x: 0, y: 1, z: 0, s: 10 }],

  [VMDBoneNames.LeftFootIK, { x: 1, y: 1, z: 0, s: 10, dx: true }],

  [VMDBoneNames.RightFootIK, { x: -1, y: 1, z: 0, s: 10, dx: true }],

  [VMDBoneNames.LeftToeIK, { x: 0, y: 0, z: 0, s: 10, o:4, dx: true, dz: true, dy: true }],

  [VMDBoneNames.RightToeIK, { x: 0, y: 0, z: 0, s: 10, o: 4, dx: true, dz: true, dy: true }],

]);
`

I tried a lot of values to try to solve this problem, but they are not ideal. 
I don’t know much about VRM models and VMD animation principles.
so can you help me to fix this problem？ thanks！
this file is my dance animation file。
[wavefile_v2.zip](https://github.com/JLChnToZ/vrm-dance-viewer/files/6552147/wavefile_v2.zip)

![image](https://user-images.githubusercontent.com/23272938/119787191-8b6e4980-bf03-11eb-8ef3-320bd3c36440.png)

**Comment by JLChnToZ** [comment]
Unfortunately, I've tried lots of value to make it as flat as I can too, but it never success. So I gave up at this point, sorry.

**Comment by JLChnToZ** [comment]
The reason why the toe IK is not mapped properly is because there is no consistant method to do so, the IK init values are just roughly deal with animation for default Miku MMD model.

**Comment by Seikida** [comment]
Hello @JLChnToZ 

Can you help to?
I would like to debug this: (Click on the youtube video)

[![IMAGE ALT TEXT HERE](https://i.ytimg.com/vi/VMtRFTRFf6w/maxresdefault.jpg)](https://www.youtube.com/watch?v=VMtRFTRFf6w)

Link: https://youtu.be/VMtRFTRFf6w

Where should I add console.log() and breakpoint ?

Best Regards

**Comment by JLChnToZ** [comment]
The implementation is in the webworker side so if you want to debug it you may head into `src/worker` and have a look
