### ISSUE TITLE
I have downloaded this project however it doesn't work...

### ISSUE THREAD

**Issue by hulihan-start** [JLChnToZ/vrm-dance-viewer#2]
In your webpage https://moka-rin.moe/vrm-viewer/ , it's performance is very good. So I want to know which of codes is the most important to make the vrm-model act...

I have used sublimetext3 and start a simple sublimeserver, however it doesn't work...

Thanks a lot!!!

**Comment by JLChnToZ** [comment]
Hi, the VRM viewer webpage is hosted on a static web server, it does not require any server code to support. If you want to run locally, it should be fine after you build the source files (using `npm run build` or `yarn build`, depends on what package manager you are using) and point your local server to `public/` folder.

**Comment by JLChnToZ** [comment]
If you want to see the code for animation, just head in to `src/worker`, most of the heavy stuff happens in the WebWorker over there.

**Comment by hulihan-start** [comment]
I can't run this in my PC... When I use npm install, it work and return this :
found 12 vulnerabilities (2 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details



When I use  npm run build it also reports errors:

npm ERR! Invalid version: "0"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SPL\AppData\Roaming\npm-cache\_logs\2021-06-28T05_37_51_238Z-debug.log

**Comment by hulihan-start** [comment]
I change the version code in package.json, and it reports another error:
ERROR in ./src/main.ts
Module build failed: Error: Final loader (./node_modules/awesome-typescript-loader/dist/entry.js) didn't return a Buffer or String
    at processResult (C:\Users\SPL\Desktop\vrm-dance-viewer\node_modules\webpack\lib\NormalModule.js:717:17)
    at C:\Users\SPL\Desktop\vrm-dance-viewer\node_modules\webpack\lib\NormalModule.js:807:5
    at C:\Users\SPL\Desktop\vrm-dance-viewer\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (C:\Users\SPL\Desktop\vrm-dance-viewer\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at iterateNormalLoaders (C:\Users\SPL\Desktop\vrm-dance-viewer\node_modules\loader-runner\lib\LoaderRunner.js:239:10)
    at C:\Users\SPL\Desktop\vrm-dance-viewer\node_modules\loader-runner\lib\LoaderRunner.js:254:3
    at context.callback (C:\Users\SPL\Desktop\vrm-dance-viewer\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

webpack 5.40.0 compiled with 1 error in 753 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vrm-dance-viewer@1.0.0 build: `webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vrm-dance-viewer@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SPL\AppData\Roaming\npm-cache\_logs\2021-06-28T05_41_15_999Z-debug.log

Is there anything wrong in my environment? I haven't debug this language before... Thanks a lot!
