### ISSUE TITLE
Color and movement differs from demo site

### ISSUE THREAD

**Issue by syui** [JLChnToZ/vrm-dance-viewer#5]
The movement and colors of the model differ from the demo. How can I adjust them?Thanks for listening to me.

<img src="https://raw.githubusercontent.com/syui/img/master/other/ai_vrm_0002.png" width="300">
<img src="https://raw.githubusercontent.com/syui/img/master/other/ai_vrm_0003.png" width="300">

demo : https://moka-rin.moe/vrm-viewer/

build : https://syui.github.io/vrm-dance-viewer

**Comment by JLChnToZ** [comment]
I'm not maintaining this project for too long, and it might have some dependency module updated, so I can't guarantee it is the same if you build it yourself.

**Comment by syui** [comment]
Yes, it is true.
Where is the movement of the hair controlled?

**Comment by JLChnToZ** [comment]
That is spring bone, and those logic are handled by [three-vrm](https://github.com/pixiv/three-vrm), I don't have any code to calculate it, just calling the API in update loop.

**Comment by syui** [comment]
Thanks, I'll try adjusting the node and three-vrm version.
